use customer_behavior;
select * from customer limit 20;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) revenue from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from customer
where discount_applied ='yes' and purchase_amount >= (select avg(purchase_amount)from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
Select item_purchased,round(AVG(review_rating),2) Avg_pro_rating from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,round(AVG(purchase_amount),2)  from customer
where shipping_type in('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,count(customer_id)as total_customer, avg(purchase_amount)as avg_spend,
sum(purchase_amount)as total_revenue from customer
group by subscription_status
order by total_revenue,avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied ='Yes' then 1 else 0 end )/ count(*),2) as discount_rate
from customer 
group by item_purchased
order by discount_rate;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (select customer_id,previous_purchases, case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment from customer)
select customer_segment,count(*) as 'Number_of_Customer'
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
  SELECT
    category,
    item_purchased,
    COUNT(customer_id) AS total_orders
  FROM customer
  GROUP BY category, item_purchased
),

ranked AS (
  SELECT category,item_purchased,total_orders,
    ROW_NUMBER() OVER (PARTITION BY category ORDER BY total_orders DESC
    ) AS item_rank FROM item_counts)

SELECT item_rank, category, item_purchased, total_orders
FROM ranked
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) repeat_buyer 
from customer 
where previous_purchases >5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_groups,SUM(purchase_amount) total_revenue 
from customer
group by age_groups
order by total_revenue desc;